name: Static check

on:
  pull_request:
    branches:
      - main
  push:
    branches: '*'
    tags: '*'

jobs:
  formatting-check:
    name: formatting-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: Check formatting
        run: poetry run black --check .
      